# Use CrateDB with Open WebUI
#
# https://cratedb.com/docs/
# https://docs.openwebui.com/getting-started/quick-start
---
networks:
  llm-demo:
    name: llm-demo
    driver: bridge

volumes:
  cratedb:
  open-webui:
  jupyter:

services:

  # -------
  # CrateDB
  # -------
  cratedb:
    image: docker.io/crate/crate:6.0.0
    environment:
      CRATE_HEAP_SIZE: 2g
    ports:
      - "4200:4200"
      - "5432:5432"
    command: [
      "crate",
      "-Cdiscovery.type=single-node",
      "-Ccluster.routing.allocation.disk.threshold_enabled=false",
    ]
    networks:
      - llm-demo
    volumes:
      - cratedb:/data
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:4200" ]
      start_period: 3s
      interval: 10s

  # ------------
  # CrateDB MCPO
  # ------------
  cratedb-mcpo:
    image: ghcr.io/crate/cratedb-mcpo:0.0.7
    environment:
      CRATEDB_CLUSTER_URL: http://crate:crate@cratedb:4200/
    ports:
      - "5200:8000"
    networks:
      - llm-demo
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8000/docs" ]
      start_period: 3s
      interval: 10s
    depends_on:
      cratedb:
        condition: service_healthy

  # ----------
  # Open WebUI
  # ----------
  open-webui:
    image: ghcr.io/open-webui/open-webui:0.6.18
    # https://docs.openwebui.com/getting-started/env-configuration
    # https://docs.openwebui.com/getting-started/api-endpoints/#swagger-documentation-links
    environment:
      # From caller's environment or `.env` file.
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      # Currently defined here.
      ENABLE_SIGNUP: "false"
      ENABLE_LOGIN_FORM: "false"
      WEBUI_AUTH: "false"
      DEFAULT_MODELS: "gpt-4.1"
      DEFAULT_USER_ROLE: "admin"
      ENABLE_CHANNELS: "true"
      RESPONSE_WATERMARK: "This text is AI generated"
      WEBUI_NAME: "CrateDB LLM Cockpit"
      BYPASS_MODEL_ACCESS_CONTROL: "true"
      ENABLE_OLLAMA_API: "false"
      ENABLE_OPENAI_API: "true"
      ENABLE_DIRECT_CONNECTIONS: "true"
      ENV: "dev"
      # Jupyter code execution and interpreter.
      ENABLE_CODE_INTERPRETER: "true"
      CODE_EXECUTION_ENGINE: "jupyter"
      CODE_EXECUTION_JUPYTER_URL: "http://jupyter:8888"
      CODE_EXECUTION_JUPYTER_AUTH: "token"
      CODE_EXECUTION_JUPYTER_AUTH_TOKEN: "123456"
      CODE_EXECUTION_JUPYTER_TIMEOUT: 60
      CODE_INTERPRETER_ENGINE: "jupyter"
      CODE_INTERPRETER_JUPYTER_URL: "http://jupyter:8888"
      CODE_INTERPRETER_JUPYTER_AUTH: "token"
      CODE_INTERPRETER_JUPYTER_AUTH_TOKEN: "123456"
      CODE_INTERPRETER_JUPYTER_TIMEOUT: 60
    ports:
      - "6200:8080"
    networks:
      - llm-demo
    volumes:
      - open-webui:/app/backend/data
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080" ]
      start_period: 3s
      interval: 10s
      retries: 60
      timeout: 90s
    depends_on:
      cratedb-mcpo:
        condition: service_healthy
      jupyter:
        condition: service_healthy

  # -------
  # Jupyter
  # -------
  jupyter:
    image: quay.io/jupyter/minimal-notebook:notebook-7.4.4
    # https://docs.openwebui.com/tutorials/jupyter/
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "123456"
    ports:
      - "7200:8888"
    networks:
      - llm-demo
    volumes:
      - jupyter:/home/jovyan/work
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8888" ]
      start_period: 3s
      interval: 10s
      retries: 60
      timeout: 90s

  # -----
  # Setup
  # -----
  setup:
    build:
      context: init
    command: bash /app/setup.sh
    networks:
      - llm-demo
    depends_on:
      cratedb:
        condition: service_healthy
      cratedb-mcpo:
        condition: service_healthy
      open-webui:
        condition: service_healthy

  # ----
  # Test
  # ----
  test:
    build:
      context: init
    command: bash /app/test.sh
    networks:
      - llm-demo
    depends_on:
      setup:
        condition: service_completed_successfully
    deploy:
      replicas: 0
