name: "llm"

on:
  pull_request:
    paths:
    - '.github/workflows/ml-llm.yml'
    - 'topic/machine-learning/llm/**'
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/ml-llm.yml'
    - 'topic/machine-learning/llm/**'

  # Allow job to be triggered manually.
  workflow_dispatch:

  # Run job each night after CrateDB nightly has been published.
  # schedule:
  #   - cron: '0 3 * * *'

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]

    env:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      UV_SYSTEM_PYTHON: 1
      UV_BREAK_SYSTEM_PACKAGES: 1

    name: OS ${{ matrix.os }}
    steps:

      - name: Acquire sources
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Validate topic/machine-learning/llm
        run: |
          # TODO: Generalize invocation into `ngr` test runner.
          cd topic/machine-learning/llm
          uv pip install -r requirements.txt
          uvx xonsh test.xsh
